/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonShape, ButtonStatus, ButtonStyle, ButtonType, IconPosition } from "./components/atoms/ss-button/ss-button";
import { Size } from "./types/size";
import { Variant } from "./types/variant";
import { InputStyle, SsInputType } from "./components/atoms/ss-input/ss-input";
import { Event } from "@stencil/core";
export { ButtonShape, ButtonStatus, ButtonStyle, ButtonType, IconPosition } from "./components/atoms/ss-button/ss-button";
export { Size } from "./types/size";
export { Variant } from "./types/variant";
export { InputStyle, SsInputType } from "./components/atoms/ss-input/ss-input";
export { Event } from "@stencil/core";
export namespace Components {
    /**
     * Botón versátil para acciones del usuario:
     * - Variantes (primary, secondary…)
     * - Tamaños (xs–xl)
     * - Estilos (solid, outline, ghost)
     * - Formas (rounded, pill, circle, square)
     * - Control de estado (loading, disabled)
     */
    interface SsButton {
        /**
          * Milisegundos que dura la deshabilitación
         */
        "disableDuration": number;
        /**
          * Deshabilitado global
         */
        "disabled": boolean;
        /**
          * Ocupa todo el ancho del contenedor
         */
        "fullWidth": boolean;
        /**
          * Posición del ícono: left|right|only
         */
        "iconPosition": IconPosition;
        /**
          * Estilos personalizados
         */
        "inlineStyles"?: string | Record<string, string>;
        /**
          * Texto interno o slot default
         */
        "label"?: string;
        /**
          * Sólo un clic: tras disparar ssClick el botón se deshabilita durante disableDuration
         */
        "oneClick": boolean;
        /**
          * Forma del botón
         */
        "shape": ButtonShape;
        /**
          * Tamaño: xs, sm, md, lg, xl
         */
        "size": Size;
        /**
          * Estado inicial: active|disabled|loading
         */
        "status": ButtonStatus;
        /**
          * Tipo de botón: `button`|`submit`|`reset`
         */
        "type": ButtonType;
        /**
          * Variante de color
         */
        "variant": Variant;
        /**
          * Atributo `id` del botón
         */
        "xId"?: string;
        /**
          * Estilo visual
         */
        "xStyle": ButtonStyle;
    }
    /**
     * Componente de entrada de texto versátil con soporte para múltiples eventos y estilos.
     * - Soporta varios tipos de entrada (texto, contraseña, email, etc.)
     * - Emit eventos para entrada, cambio, enfoque, teclado, selección, portapapeles y más.
     * - Permite estilos personalizados a través de propiedades y clases.
     * - Incluye soporte para validación HTML y eventos de interacción del usuario.
     * - Compatible con diferentes tamaños y variantes de color.
     * - Soporta estilos de entrada como sólido, contorno y subrayado.
     * *
     * @example <ss-input
     * x-id="my-input"
     * type="text"
     * color="primary"
     * value="Hello World"
     * placeholder="Enter text"
     * inline-styles="background-color: lightblue; border: 1px solid blue;"
     * size="md"
     * full-width
     * x-style="solid"
     * ></ss-input>
     */
    interface SsInput {
        /**
          * Color del componente, basado en variantes predefinidas
         */
        "color": Variant;
        /**
          * Indica si el input está deshabilitado
         */
        "disabled": boolean;
        /**
          * Indica si el input debe ocupar todo el ancho disponible
         */
        "fullWidth": boolean;
        /**
          * Estilos en línea personalizados, pueden ser una cadena o un objeto
         */
        "inlineStyles"?: string | Record<string, string>;
        /**
          * Texto de marcador de posición
         */
        "placeholder"?: string;
        /**
          * Tamaño del input, puede ser 'sm', 'md', 'lg'
         */
        "size": Size;
        /**
          * Tipo de entrada HTML
         */
        "type": SsInputType;
        /**
          * Valor actual del input
         */
        "value"?: string;
        /**
          * Identificador único para el componente
         */
        "xId": string;
        /**
          * Estilo del input, puede ser 'solid', 'outline', 'underline'
         */
        "xStyle": InputStyle;
    }
    /**
     * Componente de tipografía versátil para mostrar texto:
     * - Variantes de color (dark, light, primary, secondary)
     * - Tamaños de fuente (xs, sm, md, lg, xl)
     * - Alineación de texto (left, center, right, justify)
     * - Estilos de fuente (light, regular, medium, bold)
     * - Alturas de línea (tight, normal, relaxed)
     * - Espaciado de letras (tight, normal, wide)
     * - Personalización de estilos
     */
    interface SsTypography {
        /**
          * The text alignment for the typography component
          * @default 'left'
         */
        "align": 'left' | 'center' | 'right' | 'justify';
        /**
          * The HTML tag to be used for the typography component
          * @default 'p'
         */
        "as": 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        /**
          * The variant of the typography component
          * @default 'dark'
         */
        "color": Variant | 'black' | 'white';
        /**
          * The size of the typography component
          * @default 'md'
         */
        "fontSize": Size;
        /**
          * The font weight of the typography component
          * @default 'regular'
         */
        "fontWeight": 'light' | 'regular' | 'medium' | 'bold';
        /**
          * | Custom styles for the typography component
          * @default {}
         */
        "inlineStyles": { [key: string]: string } | string;
        /**
          * The letter spacing of the typography component
          * @default 'normal'
         */
        "letterSpacing": 'tight' | 'normal' | 'wide';
        /**
          * The line height of the typography component
          * @default 'normal'
         */
        "lineHeight": 'tight' | 'normal' | 'relaxed';
        /**
          * If true, the text will be displayed in uppercase
         */
        "transform": 'uppercase' | 'lowercase' | 'capitalize' | 'normal';
        /**
          * If true, the text will be truncated with an ellipsis if it overflows its container
         */
        "truncate": boolean;
        /**
          * id del componente tipográfico
         */
        "xId": string;
    }
}
export interface SsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsButtonElement;
}
export interface SsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsInputElement;
}
declare global {
    interface HTMLSsButtonElementEventMap {
        "ssClick": string;
    }
    /**
     * Botón versátil para acciones del usuario:
     * - Variantes (primary, secondary…)
     * - Tamaños (xs–xl)
     * - Estilos (solid, outline, ghost)
     * - Formas (rounded, pill, circle, square)
     * - Control de estado (loading, disabled)
     */
    interface HTMLSsButtonElement extends Components.SsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSsButtonElementEventMap>(type: K, listener: (this: HTMLSsButtonElement, ev: SsButtonCustomEvent<HTMLSsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSsButtonElementEventMap>(type: K, listener: (this: HTMLSsButtonElement, ev: SsButtonCustomEvent<HTMLSsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSsButtonElement: {
        prototype: HTMLSsButtonElement;
        new (): HTMLSsButtonElement;
    };
    interface HTMLSsInputElementEventMap {
        "ssInput": { xId: string; value: string };
        "ssChange": { xId: string; value: string };
        "ssBeforeInput": { xId: string; data: string };
        "ssInvalid": { xId: string; value: string };
        "ssFocus": FocusEvent;
        "ssBlur": FocusEvent;
        "ssFocusIn": FocusEvent;
        "ssFocusOut": FocusEvent;
        "ssKeyDown": KeyboardEvent;
        "ssKeyPress": KeyboardEvent;
        "ssKeyUp": KeyboardEvent;
        "ssSelect": Event;
        "ssCompositionStart": CompositionEvent;
        "ssCompositionUpdate": CompositionEvent;
        "ssCompositionEnd": CompositionEvent;
        "ssCut": ClipboardEvent;
        "ssCopy": ClipboardEvent;
        "ssPaste": ClipboardEvent;
        "ssClick": MouseEvent;
        "ssDoubleClick": MouseEvent;
        "ssMouseDown": MouseEvent;
        "ssMouseUp": MouseEvent;
        "ssMouseEnter": MouseEvent;
        "ssMouseLeave": MouseEvent;
        "ssMouseOver": MouseEvent;
        "ssMouseOut": MouseEvent;
        "ssMouseMove": MouseEvent;
        "ssContextMenu": MouseEvent;
        "ssDragStart": DragEvent;
        "ssDrag": DragEvent;
        "ssDragEnter": DragEvent;
        "ssDragLeave": DragEvent;
        "ssDragOver": DragEvent;
        "ssDrop": DragEvent;
        "ssDragEnd": DragEvent;
        "ssWheel": WheelEvent;
        "ssTouchStart": TouchEvent;
        "ssTouchMove": TouchEvent;
        "ssTouchEnd": TouchEvent;
        "ssTouchCancel": TouchEvent;
    }
    /**
     * Componente de entrada de texto versátil con soporte para múltiples eventos y estilos.
     * - Soporta varios tipos de entrada (texto, contraseña, email, etc.)
     * - Emit eventos para entrada, cambio, enfoque, teclado, selección, portapapeles y más.
     * - Permite estilos personalizados a través de propiedades y clases.
     * - Incluye soporte para validación HTML y eventos de interacción del usuario.
     * - Compatible con diferentes tamaños y variantes de color.
     * - Soporta estilos de entrada como sólido, contorno y subrayado.
     * *
     * @example <ss-input
     * x-id="my-input"
     * type="text"
     * color="primary"
     * value="Hello World"
     * placeholder="Enter text"
     * inline-styles="background-color: lightblue; border: 1px solid blue;"
     * size="md"
     * full-width
     * x-style="solid"
     * ></ss-input>
     */
    interface HTMLSsInputElement extends Components.SsInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSsInputElementEventMap>(type: K, listener: (this: HTMLSsInputElement, ev: SsInputCustomEvent<HTMLSsInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSsInputElementEventMap>(type: K, listener: (this: HTMLSsInputElement, ev: SsInputCustomEvent<HTMLSsInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSsInputElement: {
        prototype: HTMLSsInputElement;
        new (): HTMLSsInputElement;
    };
    /**
     * Componente de tipografía versátil para mostrar texto:
     * - Variantes de color (dark, light, primary, secondary)
     * - Tamaños de fuente (xs, sm, md, lg, xl)
     * - Alineación de texto (left, center, right, justify)
     * - Estilos de fuente (light, regular, medium, bold)
     * - Alturas de línea (tight, normal, relaxed)
     * - Espaciado de letras (tight, normal, wide)
     * - Personalización de estilos
     */
    interface HTMLSsTypographyElement extends Components.SsTypography, HTMLStencilElement {
    }
    var HTMLSsTypographyElement: {
        prototype: HTMLSsTypographyElement;
        new (): HTMLSsTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "ss-button": HTMLSsButtonElement;
        "ss-input": HTMLSsInputElement;
        "ss-typography": HTMLSsTypographyElement;
    }
}
declare namespace LocalJSX {
    /**
     * Botón versátil para acciones del usuario:
     * - Variantes (primary, secondary…)
     * - Tamaños (xs–xl)
     * - Estilos (solid, outline, ghost)
     * - Formas (rounded, pill, circle, square)
     * - Control de estado (loading, disabled)
     */
    interface SsButton {
        /**
          * Milisegundos que dura la deshabilitación
         */
        "disableDuration"?: number;
        /**
          * Deshabilitado global
         */
        "disabled"?: boolean;
        /**
          * Ocupa todo el ancho del contenedor
         */
        "fullWidth"?: boolean;
        /**
          * Posición del ícono: left|right|only
         */
        "iconPosition"?: IconPosition;
        /**
          * Estilos personalizados
         */
        "inlineStyles"?: string | Record<string, string>;
        /**
          * Texto interno o slot default
         */
        "label"?: string;
        /**
          * Se dispara cuando el usuario hace click
          * @event ssClick Emite el `xid` del botón
         */
        "onSsClick"?: (event: SsButtonCustomEvent<string>) => void;
        /**
          * Sólo un clic: tras disparar ssClick el botón se deshabilita durante disableDuration
         */
        "oneClick"?: boolean;
        /**
          * Forma del botón
         */
        "shape"?: ButtonShape;
        /**
          * Tamaño: xs, sm, md, lg, xl
         */
        "size"?: Size;
        /**
          * Estado inicial: active|disabled|loading
         */
        "status"?: ButtonStatus;
        /**
          * Tipo de botón: `button`|`submit`|`reset`
         */
        "type"?: ButtonType;
        /**
          * Variante de color
         */
        "variant"?: Variant;
        /**
          * Atributo `id` del botón
         */
        "xId"?: string;
        /**
          * Estilo visual
         */
        "xStyle"?: ButtonStyle;
    }
    /**
     * Componente de entrada de texto versátil con soporte para múltiples eventos y estilos.
     * - Soporta varios tipos de entrada (texto, contraseña, email, etc.)
     * - Emit eventos para entrada, cambio, enfoque, teclado, selección, portapapeles y más.
     * - Permite estilos personalizados a través de propiedades y clases.
     * - Incluye soporte para validación HTML y eventos de interacción del usuario.
     * - Compatible con diferentes tamaños y variantes de color.
     * - Soporta estilos de entrada como sólido, contorno y subrayado.
     * *
     * @example <ss-input
     * x-id="my-input"
     * type="text"
     * color="primary"
     * value="Hello World"
     * placeholder="Enter text"
     * inline-styles="background-color: lightblue; border: 1px solid blue;"
     * size="md"
     * full-width
     * x-style="solid"
     * ></ss-input>
     */
    interface SsInput {
        /**
          * Color del componente, basado en variantes predefinidas
         */
        "color"?: Variant;
        /**
          * Indica si el input está deshabilitado
         */
        "disabled"?: boolean;
        /**
          * Indica si el input debe ocupar todo el ancho disponible
         */
        "fullWidth"?: boolean;
        /**
          * Estilos en línea personalizados, pueden ser una cadena o un objeto
         */
        "inlineStyles"?: string | Record<string, string>;
        /**
          * Emitted before the value is actually inserted (cancellable)
         */
        "onSsBeforeInput"?: (event: SsInputCustomEvent<{ xId: string; data: string }>) => void;
        "onSsBlur"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value is “committed” (on blur or Enter)
         */
        "onSsChange"?: (event: SsInputCustomEvent<{ xId: string; value: string }>) => void;
        /**
          * Mouse/pointer events
         */
        "onSsClick"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsCompositionEnd"?: (event: SsInputCustomEvent<CompositionEvent>) => void;
        "onSsCompositionStart"?: (event: SsInputCustomEvent<CompositionEvent>) => void;
        "onSsCompositionUpdate"?: (event: SsInputCustomEvent<CompositionEvent>) => void;
        "onSsContextMenu"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsCopy"?: (event: SsInputCustomEvent<ClipboardEvent>) => void;
        /**
          * Clipboard events
         */
        "onSsCut"?: (event: SsInputCustomEvent<ClipboardEvent>) => void;
        "onSsDoubleClick"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsDrag"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragEnd"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragEnter"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragLeave"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragOver"?: (event: SsInputCustomEvent<DragEvent>) => void;
        /**
          * Drag & drop
         */
        "onSsDragStart"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDrop"?: (event: SsInputCustomEvent<DragEvent>) => void;
        /**
          * Focus events
         */
        "onSsFocus"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        "onSsFocusIn"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        "onSsFocusOut"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on each keystroke
         */
        "onSsInput"?: (event: SsInputCustomEvent<{ xId: string; value: string }>) => void;
        /**
          * Emitted when the control fails HTML/constraint validation
         */
        "onSsInvalid"?: (event: SsInputCustomEvent<{ xId: string; value: string }>) => void;
        /**
          * Keyboard events
         */
        "onSsKeyDown"?: (event: SsInputCustomEvent<KeyboardEvent>) => void;
        "onSsKeyPress"?: (event: SsInputCustomEvent<KeyboardEvent>) => void;
        "onSsKeyUp"?: (event: SsInputCustomEvent<KeyboardEvent>) => void;
        "onSsMouseDown"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseEnter"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseLeave"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseMove"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseOut"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseOver"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseUp"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsPaste"?: (event: SsInputCustomEvent<ClipboardEvent>) => void;
        /**
          * Text selection & IME composition
         */
        "onSsSelect"?: (event: SsInputCustomEvent<Event>) => void;
        "onSsTouchCancel"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        "onSsTouchEnd"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        "onSsTouchMove"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        /**
          * Touch events
         */
        "onSsTouchStart"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        /**
          * Wheel (scroll)
         */
        "onSsWheel"?: (event: SsInputCustomEvent<WheelEvent>) => void;
        /**
          * Texto de marcador de posición
         */
        "placeholder"?: string;
        /**
          * Tamaño del input, puede ser 'sm', 'md', 'lg'
         */
        "size"?: Size;
        /**
          * Tipo de entrada HTML
         */
        "type"?: SsInputType;
        /**
          * Valor actual del input
         */
        "value"?: string;
        /**
          * Identificador único para el componente
         */
        "xId"?: string;
        /**
          * Estilo del input, puede ser 'solid', 'outline', 'underline'
         */
        "xStyle"?: InputStyle;
    }
    /**
     * Componente de tipografía versátil para mostrar texto:
     * - Variantes de color (dark, light, primary, secondary)
     * - Tamaños de fuente (xs, sm, md, lg, xl)
     * - Alineación de texto (left, center, right, justify)
     * - Estilos de fuente (light, regular, medium, bold)
     * - Alturas de línea (tight, normal, relaxed)
     * - Espaciado de letras (tight, normal, wide)
     * - Personalización de estilos
     */
    interface SsTypography {
        /**
          * The text alignment for the typography component
          * @default 'left'
         */
        "align"?: 'left' | 'center' | 'right' | 'justify';
        /**
          * The HTML tag to be used for the typography component
          * @default 'p'
         */
        "as"?: 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        /**
          * The variant of the typography component
          * @default 'dark'
         */
        "color"?: Variant | 'black' | 'white';
        /**
          * The size of the typography component
          * @default 'md'
         */
        "fontSize"?: Size;
        /**
          * The font weight of the typography component
          * @default 'regular'
         */
        "fontWeight"?: 'light' | 'regular' | 'medium' | 'bold';
        /**
          * | Custom styles for the typography component
          * @default {}
         */
        "inlineStyles"?: { [key: string]: string } | string;
        /**
          * The letter spacing of the typography component
          * @default 'normal'
         */
        "letterSpacing"?: 'tight' | 'normal' | 'wide';
        /**
          * The line height of the typography component
          * @default 'normal'
         */
        "lineHeight"?: 'tight' | 'normal' | 'relaxed';
        /**
          * If true, the text will be displayed in uppercase
         */
        "transform"?: 'uppercase' | 'lowercase' | 'capitalize' | 'normal';
        /**
          * If true, the text will be truncated with an ellipsis if it overflows its container
         */
        "truncate"?: boolean;
        /**
          * id del componente tipográfico
         */
        "xId"?: string;
    }
    interface IntrinsicElements {
        "ss-button": SsButton;
        "ss-input": SsInput;
        "ss-typography": SsTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Botón versátil para acciones del usuario:
             * - Variantes (primary, secondary…)
             * - Tamaños (xs–xl)
             * - Estilos (solid, outline, ghost)
             * - Formas (rounded, pill, circle, square)
             * - Control de estado (loading, disabled)
             */
            "ss-button": LocalJSX.SsButton & JSXBase.HTMLAttributes<HTMLSsButtonElement>;
            /**
             * Componente de entrada de texto versátil con soporte para múltiples eventos y estilos.
             * - Soporta varios tipos de entrada (texto, contraseña, email, etc.)
             * - Emit eventos para entrada, cambio, enfoque, teclado, selección, portapapeles y más.
             * - Permite estilos personalizados a través de propiedades y clases.
             * - Incluye soporte para validación HTML y eventos de interacción del usuario.
             * - Compatible con diferentes tamaños y variantes de color.
             * - Soporta estilos de entrada como sólido, contorno y subrayado.
             * *
             * @example <ss-input
             * x-id="my-input"
             * type="text"
             * color="primary"
             * value="Hello World"
             * placeholder="Enter text"
             * inline-styles="background-color: lightblue; border: 1px solid blue;"
             * size="md"
             * full-width
             * x-style="solid"
             * ></ss-input>
             */
            "ss-input": LocalJSX.SsInput & JSXBase.HTMLAttributes<HTMLSsInputElement>;
            /**
             * Componente de tipografía versátil para mostrar texto:
             * - Variantes de color (dark, light, primary, secondary)
             * - Tamaños de fuente (xs, sm, md, lg, xl)
             * - Alineación de texto (left, center, right, justify)
             * - Estilos de fuente (light, regular, medium, bold)
             * - Alturas de línea (tight, normal, relaxed)
             * - Espaciado de letras (tight, normal, wide)
             * - Personalización de estilos
             */
            "ss-typography": LocalJSX.SsTypography & JSXBase.HTMLAttributes<HTMLSsTypographyElement>;
        }
    }
}
