/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Variant } from "./types/variant";
import { BadgeStyle, SsBadgeDismissEvent } from "./components/atoms/ss-badge/ss-badge";
import { Size } from "./types/size";
import { InlineStyles } from "./utils/style";
import { ButtonShape, ButtonStatus, ButtonStyle, ButtonType, IconPosition } from "./components/atoms/ss-button/ss-button";
import { InputStyle, SsInputType, SsInputValueEvent } from "./components/atoms/ss-input/ss-input";
import { Event } from "@stencil/core";
import { FontWeight, LetterSpacing, LineHeight, TextAlign, TextTransform, TypographyColor, TypographySize, TypographyTag } from "./components/atoms/ss-typography/ss-typography";
export { Variant } from "./types/variant";
export { BadgeStyle, SsBadgeDismissEvent } from "./components/atoms/ss-badge/ss-badge";
export { Size } from "./types/size";
export { InlineStyles } from "./utils/style";
export { ButtonShape, ButtonStatus, ButtonStyle, ButtonType, IconPosition } from "./components/atoms/ss-button/ss-button";
export { InputStyle, SsInputType, SsInputValueEvent } from "./components/atoms/ss-input/ss-input";
export { Event } from "@stencil/core";
export { FontWeight, LetterSpacing, LineHeight, TextAlign, TextTransform, TypographyColor, TypographySize, TypographyTag } from "./components/atoms/ss-typography/ss-typography";
export namespace Components {
    interface SsBadge {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'Dismiss'
         */
        "dismissLabel": string;
        /**
          * @default false
         */
        "dismissible": boolean;
        "inlineStyles"?: InlineStyles;
        "label"?: string;
        /**
          * @default false
         */
        "pill": boolean;
        /**
          * @default 'sm'
         */
        "size": Size;
        /**
          * @default 'primary'
         */
        "variant": Variant;
        "xId"?: string;
        /**
          * @default 'subtle'
         */
        "xStyle": BadgeStyle;
    }
    interface SsButton {
        /**
          * @default 1000
         */
        "disableDuration": number;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default 'right'
         */
        "iconPosition": IconPosition;
        "inlineStyles"?: InlineStyles;
        "label"?: string;
        /**
          * After ssClick fires, button is disabled for disableDuration ms
          * @default true
         */
        "oneClick": boolean;
        /**
          * @default 'rounded'
         */
        "shape": ButtonShape;
        /**
          * @default 'md'
         */
        "size": Size;
        /**
          * @default 'active'
         */
        "status": ButtonStatus;
        /**
          * @default 'button'
         */
        "type": ButtonType;
        /**
          * @default 'primary'
         */
        "variant": Variant;
        "xId"?: string;
        /**
          * @default 'solid'
         */
        "xStyle": ButtonStyle;
    }
    interface SsInput {
        /**
          * @default 'primary'
         */
        "color": Variant;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        "inlineStyles"?: InlineStyles;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": Size;
        /**
          * @default 'text'
         */
        "type": SsInputType;
        "value"?: string;
        "xId"?: string;
        /**
          * @default 'solid'
         */
        "xStyle": InputStyle;
    }
    interface SsTypography {
        /**
          * @default 'left'
         */
        "align": TextAlign;
        /**
          * @default 'p'
         */
        "as": TypographyTag;
        /**
          * 'foreground' uses the semantic foreground token and adapts to dark mode
          * @default 'foreground'
         */
        "color": TypographyColor;
        /**
          * @default 'md'
         */
        "fontSize": TypographySize;
        /**
          * @default 'regular'
         */
        "fontWeight": FontWeight;
        "inlineStyles"?: InlineStyles;
        /**
          * @default 'normal'
         */
        "letterSpacing": LetterSpacing;
        /**
          * @default 'normal'
         */
        "lineHeight": LineHeight;
        /**
          * @default 'normal'
         */
        "transform": TextTransform;
        /**
          * @default false
         */
        "truncate": boolean;
        "xId"?: string;
    }
}
export interface SsBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsBadgeElement;
}
export interface SsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsButtonElement;
}
export interface SsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsInputElement;
}
declare global {
    interface HTMLSsBadgeElementEventMap {
        "ssDismiss": SsBadgeDismissEvent;
    }
    interface HTMLSsBadgeElement extends Components.SsBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSsBadgeElementEventMap>(type: K, listener: (this: HTMLSsBadgeElement, ev: SsBadgeCustomEvent<HTMLSsBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSsBadgeElementEventMap>(type: K, listener: (this: HTMLSsBadgeElement, ev: SsBadgeCustomEvent<HTMLSsBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSsBadgeElement: {
        prototype: HTMLSsBadgeElement;
        new (): HTMLSsBadgeElement;
    };
    interface HTMLSsButtonElementEventMap {
        "ssClick": string | undefined;
    }
    interface HTMLSsButtonElement extends Components.SsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSsButtonElementEventMap>(type: K, listener: (this: HTMLSsButtonElement, ev: SsButtonCustomEvent<HTMLSsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSsButtonElementEventMap>(type: K, listener: (this: HTMLSsButtonElement, ev: SsButtonCustomEvent<HTMLSsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSsButtonElement: {
        prototype: HTMLSsButtonElement;
        new (): HTMLSsButtonElement;
    };
    interface HTMLSsInputElementEventMap {
        "ssInput": SsInputValueEvent;
        "ssChange": SsInputValueEvent;
        "ssInvalid": SsInputValueEvent;
        "ssFocus": FocusEvent;
        "ssBlur": FocusEvent;
        "ssFocusIn": FocusEvent;
        "ssFocusOut": FocusEvent;
        "ssKeyDown": KeyboardEvent;
        "ssKeyPress": KeyboardEvent;
        "ssKeyUp": KeyboardEvent;
        "ssSelect": Event;
        "ssCompositionStart": CompositionEvent;
        "ssCompositionUpdate": CompositionEvent;
        "ssCompositionEnd": CompositionEvent;
        "ssCut": ClipboardEvent;
        "ssCopy": ClipboardEvent;
        "ssPaste": ClipboardEvent;
        "ssClick": MouseEvent;
        "ssDoubleClick": MouseEvent;
        "ssMouseDown": MouseEvent;
        "ssMouseUp": MouseEvent;
        "ssMouseEnter": MouseEvent;
        "ssMouseLeave": MouseEvent;
        "ssMouseOver": MouseEvent;
        "ssMouseOut": MouseEvent;
        "ssMouseMove": MouseEvent;
        "ssContextMenu": MouseEvent;
        "ssDragStart": DragEvent;
        "ssDrag": DragEvent;
        "ssDragEnter": DragEvent;
        "ssDragLeave": DragEvent;
        "ssDragOver": DragEvent;
        "ssDrop": DragEvent;
        "ssDragEnd": DragEvent;
        "ssWheel": WheelEvent;
        "ssTouchStart": TouchEvent;
        "ssTouchMove": TouchEvent;
        "ssTouchEnd": TouchEvent;
        "ssTouchCancel": TouchEvent;
    }
    interface HTMLSsInputElement extends Components.SsInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSsInputElementEventMap>(type: K, listener: (this: HTMLSsInputElement, ev: SsInputCustomEvent<HTMLSsInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSsInputElementEventMap>(type: K, listener: (this: HTMLSsInputElement, ev: SsInputCustomEvent<HTMLSsInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSsInputElement: {
        prototype: HTMLSsInputElement;
        new (): HTMLSsInputElement;
    };
    interface HTMLSsTypographyElement extends Components.SsTypography, HTMLStencilElement {
    }
    var HTMLSsTypographyElement: {
        prototype: HTMLSsTypographyElement;
        new (): HTMLSsTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "ss-badge": HTMLSsBadgeElement;
        "ss-button": HTMLSsButtonElement;
        "ss-input": HTMLSsInputElement;
        "ss-typography": HTMLSsTypographyElement;
    }
}
declare namespace LocalJSX {
    interface SsBadge {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'Dismiss'
         */
        "dismissLabel"?: string;
        /**
          * @default false
         */
        "dismissible"?: boolean;
        "inlineStyles"?: InlineStyles;
        "label"?: string;
        "onSsDismiss"?: (event: SsBadgeCustomEvent<SsBadgeDismissEvent>) => void;
        /**
          * @default false
         */
        "pill"?: boolean;
        /**
          * @default 'sm'
         */
        "size"?: Size;
        /**
          * @default 'primary'
         */
        "variant"?: Variant;
        "xId"?: string;
        /**
          * @default 'subtle'
         */
        "xStyle"?: BadgeStyle;
    }
    interface SsButton {
        /**
          * @default 1000
         */
        "disableDuration"?: number;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default 'right'
         */
        "iconPosition"?: IconPosition;
        "inlineStyles"?: InlineStyles;
        "label"?: string;
        "onSsClick"?: (event: SsButtonCustomEvent<string | undefined>) => void;
        /**
          * After ssClick fires, button is disabled for disableDuration ms
          * @default true
         */
        "oneClick"?: boolean;
        /**
          * @default 'rounded'
         */
        "shape"?: ButtonShape;
        /**
          * @default 'md'
         */
        "size"?: Size;
        /**
          * @default 'active'
         */
        "status"?: ButtonStatus;
        /**
          * @default 'button'
         */
        "type"?: ButtonType;
        /**
          * @default 'primary'
         */
        "variant"?: Variant;
        "xId"?: string;
        /**
          * @default 'solid'
         */
        "xStyle"?: ButtonStyle;
    }
    interface SsInput {
        /**
          * @default 'primary'
         */
        "color"?: Variant;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "inlineStyles"?: InlineStyles;
        "name"?: string;
        "onSsBlur"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        "onSsChange"?: (event: SsInputCustomEvent<SsInputValueEvent>) => void;
        "onSsClick"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsCompositionEnd"?: (event: SsInputCustomEvent<CompositionEvent>) => void;
        "onSsCompositionStart"?: (event: SsInputCustomEvent<CompositionEvent>) => void;
        "onSsCompositionUpdate"?: (event: SsInputCustomEvent<CompositionEvent>) => void;
        "onSsContextMenu"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsCopy"?: (event: SsInputCustomEvent<ClipboardEvent>) => void;
        "onSsCut"?: (event: SsInputCustomEvent<ClipboardEvent>) => void;
        "onSsDoubleClick"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsDrag"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragEnd"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragEnter"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragLeave"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragOver"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDragStart"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsDrop"?: (event: SsInputCustomEvent<DragEvent>) => void;
        "onSsFocus"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        "onSsFocusIn"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        "onSsFocusOut"?: (event: SsInputCustomEvent<FocusEvent>) => void;
        "onSsInput"?: (event: SsInputCustomEvent<SsInputValueEvent>) => void;
        "onSsInvalid"?: (event: SsInputCustomEvent<SsInputValueEvent>) => void;
        "onSsKeyDown"?: (event: SsInputCustomEvent<KeyboardEvent>) => void;
        "onSsKeyPress"?: (event: SsInputCustomEvent<KeyboardEvent>) => void;
        "onSsKeyUp"?: (event: SsInputCustomEvent<KeyboardEvent>) => void;
        "onSsMouseDown"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseEnter"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseLeave"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseMove"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseOut"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseOver"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsMouseUp"?: (event: SsInputCustomEvent<MouseEvent>) => void;
        "onSsPaste"?: (event: SsInputCustomEvent<ClipboardEvent>) => void;
        "onSsSelect"?: (event: SsInputCustomEvent<Event>) => void;
        "onSsTouchCancel"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        "onSsTouchEnd"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        "onSsTouchMove"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        "onSsTouchStart"?: (event: SsInputCustomEvent<TouchEvent>) => void;
        "onSsWheel"?: (event: SsInputCustomEvent<WheelEvent>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: Size;
        /**
          * @default 'text'
         */
        "type"?: SsInputType;
        "value"?: string;
        "xId"?: string;
        /**
          * @default 'solid'
         */
        "xStyle"?: InputStyle;
    }
    interface SsTypography {
        /**
          * @default 'left'
         */
        "align"?: TextAlign;
        /**
          * @default 'p'
         */
        "as"?: TypographyTag;
        /**
          * 'foreground' uses the semantic foreground token and adapts to dark mode
          * @default 'foreground'
         */
        "color"?: TypographyColor;
        /**
          * @default 'md'
         */
        "fontSize"?: TypographySize;
        /**
          * @default 'regular'
         */
        "fontWeight"?: FontWeight;
        "inlineStyles"?: InlineStyles;
        /**
          * @default 'normal'
         */
        "letterSpacing"?: LetterSpacing;
        /**
          * @default 'normal'
         */
        "lineHeight"?: LineHeight;
        /**
          * @default 'normal'
         */
        "transform"?: TextTransform;
        /**
          * @default false
         */
        "truncate"?: boolean;
        "xId"?: string;
    }
    interface IntrinsicElements {
        "ss-badge": SsBadge;
        "ss-button": SsButton;
        "ss-input": SsInput;
        "ss-typography": SsTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ss-badge": LocalJSX.SsBadge & JSXBase.HTMLAttributes<HTMLSsBadgeElement>;
            "ss-button": LocalJSX.SsButton & JSXBase.HTMLAttributes<HTMLSsButtonElement>;
            "ss-input": LocalJSX.SsInput & JSXBase.HTMLAttributes<HTMLSsInputElement>;
            "ss-typography": LocalJSX.SsTypography & JSXBase.HTMLAttributes<HTMLSsTypographyElement>;
        }
    }
}
