name: Requeriments Library

on:
  pull_request:
    branches:
      - main

jobs:
  requeriments:
    uses: slice-soft/ss-pipeline/.github/workflows/ci-node.yml@v0
    with:
      node-version: "22"
    secrets: inherit
