name: Requeriments Library

on:
  pull_request:
    branches:
      - main

jobs:
  requeriments:
    uses: slice-soft/ss-pipeline/.github/workflows/requirements-node.yml@feature/juancadev
    with:
      node-version: 22
      project-type: library
      package-file: package.json
    secrets: inherit
